# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 87429b73ae48097e1ae0bce502c2b5702b9d4d922d80c257c3760707911ef1a899e979a79a4737d95313775fae6be4b1c9df6aa12a80d463dfe558653fa8e052

test:
  secret_key_base: 29af59e701a182228447222da4bfa0bd0803a1cd87331204a0dd8386e47ed4f8f298254e33f61e6a4e054d09a80f3d28c1246480915636479902adf14081d627

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
